[package]
name = "adventofcode-2015"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
lazy_static = "1.4.0"
md5 = "0.7.0"
num_cpus = "1.13.1"
regex = "1.5.4"
serde_json = "1.0.73"
